// import {
//   AlertTriangle,
//   ArrowRight,
//   Check,
//   ChevronLeft,
//   ChevronRight,
//   Command,
//   CreditCard,
//   File,
//   FileText,
//   HelpCircle,
//   Image,
//   Laptop,
//   Loader2,
//   LucideProps,
//   Moon,
//   MoreVertical,
//   Pizza,
//   Plus,
//   Settings,
//   SunMedium,
//   Trash,
//   Twitter,
//   User,
//   X,
//   type Icon as LucideIcon,
// } from "lucide-react"

// export type Icon = LucideIcon

// export const Icons = {
//   logo: Command,
//   close: X,
//   spinner: Loader2,
//   chevronLeft: ChevronLeft,
//   chevronRight: ChevronRight,
//   trash: Trash,
//   settings: Settings,
//   user: User,
//   arrowRight: ArrowRight,
//   help: HelpCircle,
//   pizza: Pizza,
//   sun: SunMedium,
//   moon: Moon,
//   laptop: Laptop,
//   check: Check,
//   warning: AlertTriangle,
//   moreVertical: MoreVertical,
//   creditCard: CreditCard,
//   file: File,
//   fileText: FileText,
//   image: Image,
//   plus: Plus,
//   twitter: Twitter,
// } as const
